from message_app.views.advertisement_message_views import *
from message_app.views.coupon_message_views import *
from message_app.views.encounter_message_views import *
from message_app.views.event_message_views import *
from message_app.views.graffiti_message_views import *
from message_app.views.message_views import *
from message_app.views.music_message_views import *
from message_app.views.text_image_comment_views import *
from message_app.views.video_message_views import *
from message_app.views.voice_comment_views import *
from message_app.views.voice_message_views import *
